echo "#include <iostream>"
echo "#include <cstdarg>"
echo ""
echo "using std::cout;      using std::endl;"
echo ""
echo "int main(int argc, char *argv[])"
echo "{"
  echo '    cout<< "argc = " << argc <<endl;  for (int i=0; i<argc; ++i) cout<< i <<" "<< argv[i] <<endl;'
  echo ""
  echo "    if (argc == 1) {"
    echo "        cout<< \"Usage:\\n\" << argv[0] << \" par1 par2 par3\" <<endl;"
    echo "        return 0;"
  echo "    }"
echo "    return 0;"
echo "}"
