FastFECSupervisor/src/common/FastFECSupervisor.cc:23:	throw (xdaq::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:86:	throw (xoap::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:156:xoap::MessageReference FastFECSupervisor::reset (xoap::MessageReference msg) throw (xoap::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:173:void FastFECSupervisor::ConfigureAction (toolbox::Event::Reference e) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:179:void FastFECSupervisor::StartAction (toolbox::Event::Reference e) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:185:void FastFECSupervisor::StopAction (toolbox::Event::Reference e) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:191:void FastFECSupervisor::PauseAction (toolbox::Event::Reference e) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:197:void FastFECSupervisor::ResumeAction (toolbox::Event::Reference e) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:203:void FastFECSupervisor::HaltAction (toolbox::Event::Reference e) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:209:void FastFECSupervisor::stateChanged (toolbox::fsm::FiniteStateMachine & fsm) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:216:void FastFECSupervisor::failedTransition (toolbox::Event::Reference e) throw (toolbox::fsm::exception::Exception)
FastFECSupervisor/src/common/FastFECSupervisor.cc:223:xoap::MessageReference FastFECSupervisor::Prog_DAC (xoap::MessageReference msg) throw (xoap::exception::Exception)
PixelCalibrations/src/common/PixelTemperatureCalibration.cc:79:void PixelTemperatureCalibration::loadConfigFile() throw (xdaq::exception::Exception)
PixelCalibrations/src/common/PixelTemperatureCalibration.cc:240://    in case exception is thrown
