/********************************************************************
* xmltree_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error xmltree_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablexmltree_dict();
extern void G__cpp_setup_inheritancexmltree_dict();
extern void G__cpp_setup_typetablexmltree_dict();
extern void G__cpp_setup_memvarxmltree_dict();
extern void G__cpp_setup_globalxmltree_dict();
extern void G__cpp_setup_memfuncxmltree_dict();
extern void G__cpp_setup_funcxmltree_dict();
extern void G__set_cpp_environmentxmltree_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "xmltree.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__xmltree_dictLN_TClass;
extern G__linked_taginfo G__xmltree_dictLN_TBuffer;
extern G__linked_taginfo G__xmltree_dictLN_TMemberInspector;
extern G__linked_taginfo G__xmltree_dictLN_TObject;
extern G__linked_taginfo G__xmltree_dictLN_LV;
extern G__linked_taginfo G__xmltree_dictLN_Disk;
extern G__linked_taginfo G__xmltree_dictLN_HCyl;
extern G__linked_taginfo G__xmltree_dictLN_DCU;
extern G__linked_taginfo G__xmltree_dictLN_DiskDCU;
extern G__linked_taginfo G__xmltree_dictLN_HCylDCU;

/* STUB derived class for protected member access */
