/********************************************************************
* classtree_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error classtree_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableclasstree_dict();
extern void G__cpp_setup_inheritanceclasstree_dict();
extern void G__cpp_setup_typetableclasstree_dict();
extern void G__cpp_setup_memvarclasstree_dict();
extern void G__cpp_setup_globalclasstree_dict();
extern void G__cpp_setup_memfuncclasstree_dict();
extern void G__cpp_setup_funcclasstree_dict();
extern void G__set_cpp_environmentclasstree_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "classtree.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__classtree_dictLN_TClass;
extern G__linked_taginfo G__classtree_dictLN_TBuffer;
extern G__linked_taginfo G__classtree_dictLN_TMemberInspector;
extern G__linked_taginfo G__classtree_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__classtree_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__classtree_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__classtree_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__classtree_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__classtree_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__classtree_dictLN_Disk;
extern G__linked_taginfo G__classtree_dictLN_HCyl;

/* STUB derived class for protected member access */
